services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DB_PATH: /app/data/corematch.duckdb
    volumes:
      - db_data:/app/data
    restart: on-failure

  duckdb-ui:
    build:
      context: .
      dockerfile: Dockerfile.duckdb-ui
    ports:
      - "4213:4213"
    environment:
      DB_PATH: /data/corematch.duckdb
    volumes:
      - db_data:/data
    restart: on-failure

volumes:
  db_data:
